// <auto-generated />
using System;
using CondominioAPI.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CondominioAPI.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230413172244_AlteracaoColunaNumeroBlocos")]
    partial class AlteracaoColunaNumeroBlocos
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CondominioAPI.Domain.Entities.Condominio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)")
                        .HasColumnName("COND_CNPJ");

                    b.Property<DateTime>("DataFundacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("COND_DataFundacao");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("COND_Endereco");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("COND_Nome");

                    b.Property<int?>("NumeroBlocos")
                        .HasColumnType("int")
                        .HasColumnName("COND_NumeroBlocos");

                    b.Property<int>("NumeroUnidades")
                        .HasColumnType("int")
                        .HasColumnName("COND_NumeroUnidades");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique()
                        .HasDatabaseName("IX_COND_Nome");

                    b.ToTable("TB_Condominio", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
